# Numpy
numpy is numerical python library used for numerical python .
its store data in a form of 1D 2D & 3rd.
Numpy is very fast .
numpy is mutable and fixed type.


# Application of numpy
Mathematics,
plotting,
Digital Photography,Machine Learning(Tensor)

In [1]:
 # load Numpy library
 ! pip install numpy # install the numpy
 import numpy as np

In [2]:
a=np.array([1,2,4,5],dtype='int16')   # 1D array
print(a)

[1 2 4 5]


In [3]:
b=np.array([[2,3,4],[4,5,6]])  # 2D array
print(b)

[[2 3 4]
 [4 5 6]]


In [4]:
# get dimension
a.ndim

1

In [5]:
# Get shape
a.shape



(4,)

In [6]:
b.shape

(2, 3)

In [7]:
a.dtype

dtype('int16')

## Accessing/changing specific elemnets ,rows,columns,etc

In [8]:
a=np.array([[1,2,3,4,5,6,7 ],[8,9,10,11,12,13,14]])

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [9]:
# Get a specific Element [r,c]
print(a[1,2]) # in first row i want to print 2nd columns

10


In [10]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
# Get a specific columns
a[:,3]

array([ 4, 11])

In [12]:
# Getting a little more fancy [startindex,endingindex,steps]
a[0,1:6:2]

array([2, 4, 6])

In [13]:
# change the element in array in a specific points
import numpy as np

# Create a NumPy array
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])

# Modify the element at row index 1 and column index 5
a[1, 5] = 90

# Print the array
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 90 14]]


In [14]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 90 14]]


In [15]:
# 3D example
c=np.array([[[1,2],[3,5],[5,7]]])
print(c)
print(c.ndim)

[[[1 2]
  [3 5]
  [5 7]]]
3


In [16]:
c[0,0,1]

2

#  initializing diffrent types of Arrays

In [17]:
# all 0s matrix
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
# all 1s matrix
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
# Any other number
np.full((3,2),9)

array([[9, 9],
       [9, 9],
       [9, 9]])

In [21]:
# Random decimal number
np.random.rand(3,4)

array([[0.48839281, 0.98320217, 0.2936999 , 0.29106581],
       [0.43144931, 0.74040146, 0.43733775, 0.53391654],
       [0.92664026, 0.6563681 , 0.01252801, 0.76501891]])

In [22]:
# random integer
np.random.randint(4,size=(3,4))

array([[3, 2, 0, 0],
       [0, 3, 2, 0],
       [2, 1, 1, 1]])

In [23]:
#The identity matrix
# the daiognol elemnt are one the other are zero
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# mathematics

In [24]:
# mathematics
a=np.array([1,2,3])
print(a)

[1 2 3]


In [25]:
a+2

array([3, 4, 5])

In [26]:
a*2

array([2, 4, 6])

In [27]:
a/4

array([0.25, 0.5 , 0.75])

In [28]:
 # Addition of two Arrays
 a=np.array([3,5,4,2])
 b=np.array([5,3,2,1])
 print(a+b)

[8 8 6 3]


In [29]:
print(a-b)
print(a/b)
print(a*b)

[-2  2  2  1]
[0.6        1.66666667 2.         2.        ]
[15 15  8  2]


In [30]:
np.sin(a)

array([ 0.14112001, -0.95892427, -0.7568025 ,  0.90929743])

In [31]:
np.cos(a)

array([-0.9899925 ,  0.28366219, -0.65364362, -0.41614684])

# Linear algebra

In [32]:
# Create a matrix
A = np.array([[1, 2], [3, 4]])

# Calculate the transpose
A_T = np.transpose(A)
print("Transpose:\n", A_T)

# Calculate the determinant
det = np.linalg.det(A)
print("Determinant:", det)

# Calculate the inverse
A_inv = np.linalg.inv(A)
print("Inverse:\n", A_inv)

# Perform matrix multiplication
I = np.dot(A, A_inv)
print("Product of A and its inverse (Identity Matrix):\n", I)

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Transpose:
 [[1 3]
 [2 4]]
Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Product of A and its inverse (Identity Matrix):
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


# Statistics

In [33]:
import numpy as np

# Generate a random dataset
np.random.seed(0)
data = np.random.randn(1000)

# Descriptive Statistics
mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)
variance = np.var(data)
percentiles = np.percentile(data, [25, 50, 75])
min_val = np.min(data)
max_val = np.max(data)

summary_stats = {
    "mean": mean,
    "median": median,
    "std_dev": std_dev,
    "variance": variance,
    "min": min_val,
    "max": max_val,
    "25th_percentile": percentiles[0],
    "50th_percentile": percentiles[1],
    "75th_percentile": percentiles[2]
}
print(f"Summary Statistics: {summary_stats}")

# Normal Distribution
mu, sigma = 0, 0.1
normal_dist = np.random.normal(mu, sigma, 1000)
mean_normal = np.mean(normal_dist)
std_dev_normal = np.std(normal_dist)
print(f"Normal Distribution Mean: {mean_normal}, Standard Deviation: {std_dev_normal}")

# Uniform Distribution
uniform_dist = np.random.uniform(-1, 1, 1000)
mean_uniform = np.mean(uniform_dist)
std_dev_uniform = np.std(uniform_dist)
print(f"Uniform Distribution Mean: {mean_uniform}, Standard Deviation: {std_dev_uniform}")

# Correlation and Covariance
x = np.random.rand(100)
y = 2 * x + np.random.randn(100) * 0.1

cov_matrix = np.cov(x, y)
correlation = np.corrcoef(x, y)
print(f"Covariance Matrix:\n{cov_matrix}")
print(f"Correlation Coefficient:\n{correlation}")


Summary Statistics: {'mean': -0.045256707490195384, 'median': -0.058028034799627745, 'std_dev': 0.9870331586690257, 'variance': 0.9742344563121542, 'min': -3.0461430547999266, 'max': 2.759355114021582, '25th_percentile': -0.6984200593598706, '50th_percentile': -0.058028034799627745, '75th_percentile': 0.6069506018883982}
Normal Distribution Mean: 0.0013616940316163566, Standard Deviation: 0.09681599838264231
Uniform Distribution Mean: 0.0009054088701296243, Standard Deviation: 0.5758328773084529
Covariance Matrix:
[[0.08560354 0.17298033]
 [0.17298033 0.35811031]]
Correlation Coefficient:
[[1.       0.987967]
 [0.987967 1.      ]]


# Reorganizing Arrays

In [37]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
