In [1]:
# import libraries 
import numpy as np 


NumPy is a Python library.

NumPy is used for working with arrays.

NumPy is short for "Numerical Python".

In [3]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Data Science: is a branch of computer science where we study how to store, use and analyze data for deriving information from it.

0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [5]:
arr=np.array(42)
print(arr)

42


In [12]:
# one dimentional array
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.ndim) # check the dimention of the array 

[1 2 3 4 5]
1


In [14]:
# two dimentional array
arr1=np.array([[12,3,22,24],[23,1,22,67]])
print(arr1)
print(arr1.ndim)

[[12  3 22 24]
 [23  1 22 67]]
2


In [17]:
# 3d array
arr=np.array([[[1,2,3,4],[34,2,1,4],[89,3,2,0]]])
print(arr)
print(arr.ndim)

[[[ 1  2  3  4]
  [34  2  1  4]
  [89  3  2  0]]]
3


Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.